"""M6d: Kaplan-Meier time from the day-7 landmark to the author's next note.

A plain "fraction returned by day t" curve would be wrong here: later cohorts have had
less time to come back, and without censoring they drag the curve down for reasons that
have nothing to do with the question.

Usage: python src/analysis_survival.py
"""

import csv
from pathlib import Path

import duckdb
import numpy as np
from statsmodels.duration.survfunc import SurvfuncRight, survdiff

import exclusions
import retention
from retention import STATUSES

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "out" / "tables"
K = 7
HORIZON = 90

CENSORING_RULE = (
    f"Follow-up starts at the day-{K} landmark. The event is the author's next note, at "
    f"`second_note_at − landmark_at` in days. An author with no next note is censored at "
    f"`data_cutoff_at − landmark_at`, where `data_cutoff_at` is 2026-09-16, the newest note "
    f"in the snapshot — not the 2026-09-18 snapshot date, because releases only contain "
    f"notes created up to 48 hours earlier. Durations are floored to whole days."
)


def durations(con: duckdb.DuckDBPyConnection) -> dict[str, tuple[np.ndarray, np.ndarray]]:
    landmark = retention.landmark_sql(exclusions.analysis_sql(), K)
    rows = con.execute(
        f"""
        SELECT status_k,
               floor(date_diff('second',
                 landmark_at, coalesce(second_note_at, data_cutoff_at)) / 86400.0) AS days,
               second_note_at IS NOT NULL AS event
        FROM ({landmark})
        """
    ).fetchall()
    out = {}
    for s in STATUSES:
        d = [(t, e) for st, t, e in rows if st == s]
        out[s] = (np.array([t for t, _ in d], float), np.array([e for _, e in d], int))
    return out


def curve(time: np.ndarray, event: np.ndarray) -> list[dict]:
    """KM estimate with pointwise log-log (Kalbfleisch-Prentice) 95% intervals."""
    sf = SurvfuncRight(time, event)
    s, se = sf.surv_prob, sf.surv_prob_se
    with np.errstate(divide="ignore", invalid="ignore"):
        se_loglog = se / (s * np.abs(np.log(s)))
        lo = s ** np.exp(retention.Z * se_loglog)
        hi = s ** np.exp(-retention.Z * se_loglog)
    lo, hi = np.nan_to_num(lo, nan=0.0), np.nan_to_num(hi, nan=1.0)

    rows = []
    for i, t in enumerate(sf.surv_times):
        if t > HORIZON:
            break
        rows.append(
            {
                "time_days": int(t),
                "at_risk": int(sf.n_risk[i]),
                "events": int(sf.n_events[i]),
                "survival": float(s[i]),
                "ci_low": float(lo[i]),
                "ci_high": float(hi[i]),
            }
        )
    return rows


def median_return(rows: list[dict]) -> str:
    for r in rows:
        if r["survival"] <= 0.5:
            return f"{r['time_days']} days"
    return "not reached within 90 days"


def main() -> None:
    con = duckdb.connect()
    data = durations(con)

    all_rows = []
    curves = {}
    for status in STATUSES:
        t, e = data[status]
        rows = curve(t, e)
        curves[status] = rows
        all_rows += [{"status": status, **r} for r in rows]

    TABLES.mkdir(parents=True, exist_ok=True)
    with open(TABLES / "km.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(all_rows[0].keys()))
        w.writeheader()
        w.writerows(all_rows)

    t = np.concatenate([data[s][0] for s in ("Not Helpful", "NMR")])
    e = np.concatenate([data[s][1] for s in ("Not Helpful", "NMR")])
    g = np.concatenate([np.full(len(data[s][0]), i) for i, s in enumerate(("Not Helpful", "NMR"))])
    chisq, pvalue = survdiff(t, e, g)

    L = [
        "# Survival curves (M6d)",
        "",
        "Generated by `src/analysis_survival.py`. Curve data in `out/tables/km.csv`.",
        "",
        "## Censoring rule",
        "",
        CENSORING_RULE,
        "",
        "## Returned by day 90, and median time to return",
        "",
        "| status | authors | events | returned by day 90 | median time to return |",
        "| --- | ---: | ---: | ---: | --- |",
    ]
    for s in STATUSES:
        last = curves[s][-1]
        L.append(
            f"| {s} | {len(data[s][0]):,} | {int(data[s][1].sum()):,} | "
            f"{1 - last['survival']:.1%} [{1 - last['ci_high']:.1%} – {1 - last['ci_low']:.1%}] | "
            f"{median_return(curves[s])} |"
        )
    L += [
        "",
        "Percentages are Kaplan-Meier estimates at day 90 with 95% confidence intervals,",
        "so they are not the same as the M6a proportions, which condition on a fully",
        "observed 90-day window instead of censoring.",
        "",
        "## Log-rank, Not Helpful against NMR",
        "",
        f"chi-square {chisq:.1f} on 1 df, p {'< 1e-300' if pvalue == 0 else f'= {pvalue:.3g}'}.",
        "",
        "With samples this size a significance test says very little; the interval on the",
        "difference in M6a is the number worth reading.",
    ]
    (TABLES / "km.md").write_text("\n".join(L).rstrip() + "\n")

    print(f"wrote {(TABLES / 'km.csv').relative_to(ROOT)} and km.md")
    for s in STATUSES:
        last = curves[s][-1]
        print(f"  {s:<12} n={len(data[s][0]):>7,}  returned by day 90 {1 - last['survival']:.1%}  median {median_return(curves[s])}")
    print(f"  log-rank NH vs NMR: chi2={chisq:.1f}, p={pvalue:.3g}")


if __name__ == "__main__":
    main()
