"""M6b: the same question answered the obvious way, and what that costs.

No landmark: the first note is labelled with whatever verdict it eventually got, whenever
that arrived, and retention is measured from the note itself. Censoring is kept, so the
gap against M6a isolates the landmark design rather than mixing in observation windows.

Usage: python src/analysis_naive.py
"""

import csv
from pathlib import Path

import duckdb

import exclusions
import retention
from retention import STATUSES, WINDOWS

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "out" / "tables"
K = 7


def naive_sql(sample: str) -> str:
    return f"""
    SELECT *,
      CASE first_verdict_status
        WHEN 'CURRENTLY_RATED_HELPFUL' THEN 'Helpful'
        WHEN 'CURRENTLY_RATED_NOT_HELPFUL' THEN 'Not Helpful'
        ELSE 'NMR'
      END AS status_k,
      first_note_at AS landmark_at
    FROM ({sample})
    """


def cohort_mix(con: duckdb.DuckDBPyConnection, naive: str) -> list[tuple]:
    return con.execute(
        f"""
        SELECT status_k, count(*) AS n,
               quantile_cont(epoch(first_note_at), 0.25) AS q25,
               quantile_cont(epoch(first_note_at), 0.50) AS q50,
               quantile_cont(epoch(first_note_at), 0.75) AS q75
        FROM ({retention.retention_sql(naive, 30)}) WHERE observable
        GROUP BY 1
        """
    ).fetchall()


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def render(rows, diffs, primary_diffs, mix, n_naive, n_primary) -> str:
    def find(ds, w, comp):
        return next(d for d in ds if d["window_days"] == w and d["comparison"] == comp)

    nh30, nh30p = find(diffs, 30, "Not Helpful - NMR"), find(primary_diffs, 30, "Not Helpful - NMR")
    shift = nh30["difference"] - nh30p["difference"]

    L = [
        "# Naive comparison (M6b)",
        "",
        f"Computed the obvious way, the Not Helpful minus NMR gap at 30 days is "
        f"**{nh30['difference'] * 100:+.1f} pp**. With the day-7 landmark (M6a) it is "
        f"**{nh30p['difference'] * 100:+.1f} pp**. The naive specification moves the "
        f"headline number by {shift * 100:+.1f} pp, "
        f"{'understating' if abs(nh30['difference']) < abs(nh30p['difference']) else 'overstating'} "
        "the association.",
        "",
        "Generated by `src/analysis_naive.py`. Do not hand-edit.",
        "",
        "## What changes",
        "",
        "Two things, and only two:",
        "",
        "1. The first note is labelled with the verdict it eventually received, even if that",
        f"   arrived months later. In M6a a verdict after day {K} counts as NMR, because at",
        f"   day {K} it had not happened.",
        f"2. Authors who wrote again within {K} days are kept. M6a drops them — no feedback",
        "   could have reached them, so their return is not a response to one.",
        "",
        f"Censoring is identical in both, so the difference below is the landmark design and",
        f"nothing else. The naive sample is {n_naive:,} authors at 30 days against "
        f"{n_primary:,} in M6a; the extra {n_naive - n_primary:,} are the early returners.",
        "",
        "## Naive retention",
        "",
        "| window | status | n | retained | proportion | 95% CI |",
        "| ---: | --- | ---: | ---: | ---: | --- |",
    ]
    for r in rows:
        L.append(
            f"| {r['window_days']}d | {r['status']} | {r['n']:,} | {r['retained']:,} | "
            f"{r['proportion']:.1%} | {r['ci_low']:.1%} – {r['ci_high']:.1%} |"
        )

    L += [
        "",
        "## The gap between specifications",
        "",
        "| window | comparison | naive | day-7 landmark (M6a) | naive − landmark |",
        "| ---: | --- | ---: | ---: | ---: |",
    ]
    for d in diffs:
        p = find(primary_diffs, d["window_days"], d["comparison"])
        L.append(
            f"| {d['window_days']}d | {d['comparison']} | {d['difference'] * 100:+.1f} pp | "
            f"{p['difference'] * 100:+.1f} pp | {(d['difference'] - p['difference']) * 100:+.1f} pp |"
        )

    L += [
        "",
        "## Why the naive NMR group is different",
        "",
        "It is not a clean comparison group. It absorbs every note whose verdict never came,",
        "which skews towards recent notes, and it keeps the authors who were already writing",
        "again within the week — the most engaged people in the sample — without asking",
        "whether any feedback had reached them.",
        "",
        "First-note dates by naive status, 30-day window:",
        "",
        "| status | n | 25th pct | median | 75th pct |",
        "| --- | ---: | --- | --- | --- |",
    ]
    order = {s: i for i, s in enumerate(STATUSES)}
    for status, n, q25, q50, q75 in sorted(mix, key=lambda r: order.get(r[0], 9)):
        import datetime as dt

        f = lambda e: dt.datetime.fromtimestamp(e, dt.UTC).date()
        L.append(f"| {status} | {n:,} | {f(q25)} | {f(q50)} | {f(q75)} |")

    L += [
        "",
        "That this specification is the obvious one to reach for, and that it moves the",
        f"headline by {abs(shift) * 100:.1f} pp, is itself a finding worth reporting.",
    ]
    return "\n".join(L).rstrip() + "\n"


def main() -> None:
    con = duckdb.connect()
    sample = exclusions.analysis_sql()
    naive = naive_sql(sample)
    landmark = retention.landmark_sql(sample, K)

    rows = retention.tabulate(con, naive)
    diffs = retention.differences(rows)
    primary_diffs = retention.differences(retention.tabulate(con, landmark))
    mix = cohort_mix(con, naive)

    n_naive = sum(r["n"] for r in rows if r["window_days"] == 30)
    n_primary = con.execute(
        f"SELECT count(*) FROM ({retention.retention_sql(landmark, 30)}) WHERE observable"
    ).fetchone()[0]

    for r in rows:
        r.pop("group")
    for d in diffs:
        d.pop("group")
    for d in primary_diffs:
        d.pop("group")

    write_csv(TABLES / "naive.csv", rows)
    (TABLES / "naive.md").write_text(render(rows, diffs, primary_diffs, mix, n_naive, n_primary))

    print(f"wrote {(TABLES / 'naive.md').relative_to(ROOT)}")
    for d in diffs:
        p = next(x for x in primary_diffs if x["window_days"] == d["window_days"] and x["comparison"] == d["comparison"])
        print(
            f"  {d['window_days']:>3}d {d['comparison']:<24} naive {d['difference'] * 100:+6.2f} pp   "
            f"landmark {p['difference'] * 100:+6.2f} pp   shift {(d['difference'] - p['difference']) * 100:+6.2f} pp"
        )


if __name__ == "__main__":
    main()
