"""M6a: the headline result — retention by first-note status as of day 7.

Usage: python src/analysis_primary.py
"""

import csv
import json
from pathlib import Path

import duckdb

import exclusions
import retention
from retention import STATUSES, WINDOWS

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "out" / "tables"
K = 7


def funnel(con: duckdb.DuckDBPyConnection, sample: str, landmark: str) -> list[tuple[str, int]]:
    n = lambda q: con.execute(f"SELECT count(*) FROM ({q})").fetchone()[0]
    frozen = f"read_parquet('{ROOT / 'data' / 'processed' / 'contributors.parquet'}')"
    steps = [
        ("authors in the frozen contributor table", n(f"SELECT * FROM {frozen}")),
        ("after M5 exclusions", n(sample)),
    ]
    pre = n(
        f"SELECT * FROM ({sample}) "
        f"WHERE second_note_at IS NOT NULL AND second_note_at < first_note_at + INTERVAL {K} DAY"
    )
    steps.append((f"less authors who wrote again before day {K} (no feedback could have reached them)", -pre))
    unobs = n(
        f"SELECT * FROM ({sample}) "
        f"WHERE (second_note_at IS NULL OR second_note_at >= first_note_at + INTERVAL {K} DAY) "
        f"AND first_note_at + INTERVAL {K} DAY > data_cutoff_at"
    )
    steps.append((f"less authors whose day {K} falls past the data cutoff", -unobs))
    steps.append((f"at risk at day {K}", n(landmark)))
    for w in WINDOWS:
        obs = n(f"SELECT * FROM ({retention.retention_sql(landmark, w)}) WHERE observable")
        steps.append((f"  of those, with a fully observed {w}-day window", obs))
    return steps


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def headline(diffs: list[dict]) -> str:
    d = next(r for r in diffs if r["window_days"] == 30 and r["comparison"] == "Not Helpful - NMR")
    direction = "less" if d["difference"] < 0 else "more"
    return (
        f"Contributors whose first note was rated Not Helpful within 7 days were "
        f"{abs(d['difference']) * 100:.1f} percentage points {direction} likely to write another "
        f"note in the following 30 days than contributors whose first note was still "
        f"unresolved at day 7 "
        f"(95% CI {d['ci_low'] * 100:+.1f} to {d['ci_high'] * 100:+.1f} points; "
        f"n = {d['n_status']:,} Not Helpful, {d['n_reference']:,} NMR)."
    )


def render(steps, rows, diffs) -> str:
    L = [
        "# Primary analysis: day-7 landmark (M6a)",
        "",
        headline(diffs),
        "",
        "Generated by `src/analysis_primary.py`. Do not hand-edit.",
        "",
        "This is an association, not an effect. Nobody was assigned to Not Helpful or NMR;",
        "a weak first note plausibly produces both a bad verdict and a contributor who was",
        "leaving anyway.",
        "",
        "## Method",
        "",
        f"Authors are classified by the status their first note held at day {K}. A verdict",
        f"that arrived after day {K} counts as NMR here, because at day {K} it had not",
        "happened. Authors who wrote again before the landmark are dropped: no feedback",
        "could have reached them, so their return says nothing about how they reacted to",
        "one. Retention is any further note between the landmark and the end of the window,",
        "and an author enters a window only if the whole window is inside the data cutoff.",
        "",
        "## Sample sizes",
        "",
        "| step | authors |",
        "| --- | ---: |",
    ]
    for label, n in steps:
        L.append(f"| {label} | {n:+,} |" if n < 0 else f"| {label} | {n:,} |")

    L += [
        "",
        "## Retention by day-7 status",
        "",
        "| window | status | n | retained | proportion | 95% CI |",
        "| ---: | --- | ---: | ---: | ---: | --- |",
    ]
    for r in rows:
        L.append(
            f"| {r['window_days']}d | {r['status']} | {r['n']:,} | {r['retained']:,} | "
            f"{r['proportion']:.1%} | {r['ci_low']:.1%} – {r['ci_high']:.1%} |"
        )

    L += [
        "",
        "## Differences against NMR",
        "",
        "Newcombe hybrid-score intervals, built from the two Wilson intervals.",
        "",
        "| window | comparison | difference | 95% CI |",
        "| ---: | --- | ---: | --- |",
    ]
    for d in diffs:
        L.append(
            f"| {d['window_days']}d | {d['comparison']} | {d['difference'] * 100:+.1f} pp | "
            f"{d['ci_low'] * 100:+.1f} – {d['ci_high'] * 100:+.1f} pp |"
        )
    return "\n".join(L).rstrip() + "\n"


def main() -> None:
    con = duckdb.connect()
    sample = exclusions.analysis_sql()
    landmark = retention.landmark_sql(sample, K)

    steps = funnel(con, sample, landmark)
    rows = retention.tabulate(con, landmark)
    diffs = retention.differences(rows)

    for r in rows:
        r.pop("group")
    for d in diffs:
        d.pop("group")

    write_csv(TABLES / "primary.csv", rows)
    write_csv(TABLES / "primary_differences.csv", diffs)
    (TABLES / "primary.md").write_text(render(steps, rows, diffs))

    print(headline(diffs))
    print()
    for label, n in steps:
        print(f"  {label:<70} {n:>10,}")
    print()
    for r in rows:
        print(
            f"  {r['window_days']:>3}d  {r['status']:<12} n={r['n']:>7,}  "
            f"{r['proportion']:.1%}  [{r['ci_low']:.1%}, {r['ci_high']:.1%}]"
        )
    print()
    for d in diffs:
        print(
            f"  {d['window_days']:>3}d  {d['comparison']:<24} {d['difference'] * 100:+6.2f} pp  "
            f"[{d['ci_low'] * 100:+.2f}, {d['ci_high'] * 100:+.2f}]"
        )


if __name__ == "__main__":
    main()
