"""M6c: the day-7 analysis repeated by cohort month, and either side of the lockout change.

The 2024-04-02 rule change is the point of this milestone. Before it, a first Not Helpful
note had no mechanical consequence; after it, it locks writing ability on its own. If the
Not Helpful deficit is similar either side, the deficit is not simply the lockout.

Usage: python src/analysis_cohort.py
"""

import csv
from pathlib import Path

import duckdb

import exclusions
import retention
from retention import STATUSES

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "out" / "tables"
K = 7
WINDOW = 30
MIN_CELL = 50
LOCKOUT_RULE = "2024-04"

PERIOD = (
    f"CASE WHEN cohort_month < '{LOCKOUT_RULE}' THEN 'before {LOCKOUT_RULE}' "
    f"ELSE '{LOCKOUT_RULE} onward' END AS period"
)

# From docs/system-rules.md. Only changes that plausibly move first-verdict rates.
EVENTS = {
    "2024-02": "Expanded consensus trial",
    "2024-04": "Single Not Helpful note locks writing when Writing Impact ≤ 0",
    "2024-08": "30-minute CRH stabilisation delay; multi-group models",
    "2025-03": "Minimum delay before Helpful; ≥5 positive- and ≥5 negative-factor raters",
    "2025-07": "AI Note Writer API opens",
    "2025-11": "Gaussian model added to final scoring",
}


def completeness(con: duckdb.DuckDBPyConnection) -> dict[str, bool]:
    """A cohort month is complete only if its LAST day still leaves room for the window.

    The most recent month otherwise shows only the authors who joined early enough in it
    for a window to close, which is a biased slice rather than a cohort.
    """
    return {
        m: bool(ok)
        for m, ok in con.execute(
            f"""
            SELECT cohort_month,
                   last_day(strptime(cohort_month, '%Y-%m'))
                     + INTERVAL {K} DAY + INTERVAL {WINDOW} DAY <= max(data_cutoff_at) AS complete
            FROM ({exclusions.analysis_sql()}) GROUP BY 1
            """
        ).fetchall()
    }


def rename_group(rows: list[dict], name: str) -> list[dict]:
    return [{name: r["group"], **{k: v for k, v in r.items() if k != "group"}} for r in rows]


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def render(rows, diffs, period_rows, period_diffs, complete) -> str:
    by_cell = {(r["group"], r["status"]): r for r in rows}
    months = sorted({r["group"] for r in rows})
    gap = {d["group"]: d for d in diffs if d["comparison"] == "Not Helpful - NMR"}

    before = next(d for d in period_diffs if d["group"].startswith("before") and d["comparison"] == "Not Helpful - NMR")
    after = next(d for d in period_diffs if not d["group"].startswith("before") and d["comparison"] == "Not Helpful - NMR")

    L = [
        "# Cohort breakdown (M6c)",
        "",
        f"The Not Helpful minus NMR gap at {WINDOW} days is **{before['difference'] * 100:+.1f} pp** "
        f"for cohorts before {LOCKOUT_RULE} and **{after['difference'] * 100:+.1f} pp** for cohorts "
        f"from {LOCKOUT_RULE} onward.",
        "",
        "Generated by `src/analysis_cohort.py`. Do not hand-edit.",
        "",
        "## Either side of the lockout rule change",
        "",
        "On 2024-04-02 X added a rule locking a contributor's writing ability when a note",
        "reaches Not Helpful and their Writing Impact is 0 or negative. A first-time author's",
        "Writing Impact is 0 by definition, so from that date a single Not Helpful first note",
        "mechanically blocks writing. Before it, a newcomer needed three Not Helpful notes out",
        "of their last five resolved, and one had no consequence at all.",
        "",
        "Cohorts before the change therefore cannot have been locked out by their first note.",
        "Whatever gap they show is not the lockout.",
        "",
        f"| period | status | n | retained | proportion | 95% CI |",
        "| --- | --- | ---: | ---: | ---: | --- |",
    ]
    order = {s: i for i, s in enumerate(STATUSES)}
    for r in sorted(period_rows, key=lambda r: (r["group"], order.get(r["status"], 9))):
        L.append(
            f"| {r['group']} | {r['status']} | {r['n']:,} | {r['retained']:,} | "
            f"{r['proportion']:.1%} | {r['ci_low']:.1%} – {r['ci_high']:.1%} |"
        )
    L += [
        "",
        "| period | comparison | difference | 95% CI |",
        "| --- | --- | ---: | --- |",
    ]
    for d in sorted(period_diffs, key=lambda d: (d["group"], d["comparison"])):
        L.append(
            f"| {d['group']} | {d['comparison']} | {d['difference'] * 100:+.1f} pp | "
            f"{d['ci_low'] * 100:+.1f} – {d['ci_high'] * 100:+.1f} pp |"
        )

    L += [
        "",
        f"## {WINDOW}-day retention by cohort month",
        "",
        f"Cells with fewer than {MIN_CELL} authors are marked `·` and should not be read.",
        "Months flagged partial contain only the authors who joined early enough in them for a",
        "30-day window to close before the data cutoff, so they are a biased slice of the month",
        "rather than a cohort. `cohort_complete` in the CSV carries the same information.",
        "The last column is the Not Helpful minus NMR gap with its Newcombe interval.",
        "",
        "| cohort | Helpful | Not Helpful | NMR | NH − NMR gap | event |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for m in months:
        cells = []
        for s in STATUSES:
            r = by_cell.get((m, s))
            if r is None or r["n"] < MIN_CELL:
                cells.append(f"· (n={r['n']:,})" if r else "·")
            else:
                cells.append(f"{r['proportion']:.1%} (n={r['n']:,})")
        g = gap.get(m)
        small = any(
            by_cell.get((m, s)) is None or by_cell[(m, s)]["n"] < MIN_CELL
            for s in ("Not Helpful", "NMR")
        )
        gap_cell = "·" if (g is None or small) else (
            f"{g['difference'] * 100:+.1f} pp [{g['ci_low'] * 100:+.1f}, {g['ci_high'] * 100:+.1f}]"
        )
        event = EVENTS.get(m, "")
        if not complete.get(m, False):
            event = ("partial month — window cannot close for authors who joined late; "
                     "excluded from fig3. " + event).strip()
        L.append(f"| {m} | {' | '.join(cells)} | {gap_cell} | {event} |")

    L += [
        "",
        "## Reading it",
        "",
        "The break is sharp and it lands on the rule change. Through 2023 and early 2024 the",
        "gap is small and often indistinguishable from zero — several cohorts have intervals",
        "crossing zero, and 2023-11 is faintly positive. From 2024-03 onward it jumps to",
        "between −13 and −21 pp and never returns. Not Helpful retention itself falls from",
        "around 28% in 2024-02 to 9.6% in 2024-04 and then to the 3–8% band, while Helpful and",
        "NMR retention drift down together and much more gently.",
        "",
        "2024-03 is already at −12.5 pp, which is what should be expected rather than a",
        "problem: verdicts arrive days after the note, so a note written in March 2024 could",
        "easily reach Not Helpful in April and be caught by the new rule.",
        "",
        "**The honest reading is that the lockout explains most of the headline gap, but not",
        f"all of it.** Before {LOCKOUT_RULE}, when no first note could trigger a lockout, the gap",
        f"is {before['difference'] * 100:+.1f} pp with an interval of",
        f"[{before['ci_low'] * 100:+.1f}, {before['ci_high'] * 100:+.1f}] — small, but clearly",
        f"not zero. After, it is {after['difference'] * 100:+.1f} pp, roughly",
        f"{abs(after['difference'] / before['difference']):.1f} times larger. So rejection was",
        "associated with lower retention before X made rejection mechanically block writing,",
        "and the great majority of what we now measure is the mechanism rather than",
        "discouragement.",
        "",
        "This is a limit on what the project can claim, and it should be stated in the report",
        "rather than buried. `docs/lockout.md` (M6f) bounds the mechanical share directly from",
        "enrollment states.",
        "",
        "Two reading cautions. Retention is falling for everyone over the period — NMR drops",
        "from 43.1% in 2023-01 to 17.3% in 2026-07 — so cohorts are not comparable in level,",
        "only in gap. And cells thin out at the recent end because a 30-day window must close",
        "before the data cutoff, and at the early end because the sample starts at 2023-01 by",
        "the Gate 1 decision in `docs/system-rules.md`.",
    ]
    return "\n".join(L).rstrip() + "\n"


def main() -> None:
    con = duckdb.connect()
    sample = exclusions.analysis_sql()
    landmark = retention.landmark_sql(sample, K)

    complete = completeness(con)
    rows = retention.tabulate(con, landmark, windows=[WINDOW], group_by="cohort_month")
    for r in rows:
        r["cohort_complete"] = complete.get(r["group"], False)
    diffs = retention.differences(rows)
    period_rows = retention.tabulate(con, landmark, windows=[WINDOW], group_by=PERIOD)
    period_diffs = retention.differences(period_rows)

    write_csv(TABLES / "by_cohort.csv", rename_group(rows, "cohort_month"))
    write_csv(TABLES / "by_cohort_periods.csv", rename_group(period_rows, "period"))
    write_csv(TABLES / "by_cohort_differences.csv", rename_group(diffs, "cohort_month"))
    (TABLES / "by_cohort.md").write_text(render(rows, diffs, period_rows, period_diffs, complete))
    print(f"wrote {(TABLES / 'by_cohort.md').relative_to(ROOT)}")
    for d in sorted(period_diffs, key=lambda d: (d["group"], d["comparison"])):
        print(
            f"  {d['group']:<18} {d['comparison']:<24} {d['difference'] * 100:+6.2f} pp  "
            f"[{d['ci_low'] * 100:+.2f}, {d['ci_high'] * 100:+.2f}]  n={d['n_status']:,}/{d['n_reference']:,}"
        )


if __name__ == "__main__":
    main()
