"""M7: does the headline survive the choices we made?

One row per variation, each reporting the Not Helpful minus NMR difference at 30 days.

Usage: python src/analysis_robustness.py
"""

import csv
from pathlib import Path

import duckdb

import exclusions
import retention

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "out" / "tables"
NOTES = f"read_parquet('{ROOT / 'data' / 'interim' / 'notes.parquet'}')"
BASE_K, BASE_WINDOW = 7, 30


def with_later_note_counts(landmark: str, window: int) -> str:
    """Attach the number of notes each author wrote inside the window."""
    return f"""
    WITH lm AS ({landmark})
    SELECT lm.*, count(n.noteId) AS later_notes
    FROM lm LEFT JOIN {NOTES} n
      ON n.noteAuthorParticipantId = lm.author_id
     AND n.createdAtMillis > epoch(lm.landmark_at) * 1000
     AND n.createdAtMillis <= epoch(lm.landmark_at + INTERVAL {window} DAY) * 1000
    GROUP BY ALL
    """


def run(con, label, note, *, k=BASE_K, window=BASE_WINDOW, where=None, min_notes=1) -> dict:
    sample = exclusions.analysis_sql()
    if where:
        sample = f"SELECT * FROM ({sample}) WHERE {where}"
    landmark = retention.landmark_sql(sample, k)
    retained = None
    if min_notes > 1:
        landmark = with_later_note_counts(landmark, window)
        retained = f"later_notes >= {min_notes}"

    rows = retention.tabulate(con, landmark, windows=[window], retained=retained)
    diff = next(
        d for d in retention.differences(rows) if d["comparison"] == "Not Helpful - NMR"
    )
    by_status = {r["status"]: r for r in rows}
    return {
        "variation": label,
        "note": note,
        "landmark_days": k,
        "window_days": window,
        "n_not_helpful": by_status["Not Helpful"]["n"],
        "n_nmr": by_status["NMR"]["n"],
        "retention_not_helpful": by_status["Not Helpful"]["proportion"],
        "retention_nmr": by_status["NMR"]["proportion"],
        "difference_pp": diff["difference"] * 100,
        "ci_low_pp": diff["ci_low"] * 100,
        "ci_high_pp": diff["ci_high"] * 100,
    }


def main() -> None:
    con = duckdb.connect()
    obs_90 = (
        f"first_note_at + INTERVAL {BASE_K} DAY + INTERVAL {BASE_WINDOW} DAY "
        f"+ INTERVAL 90 DAY <= data_cutoff_at"
    )
    variations = [
        run(con, "baseline (M6a)", "day-7 landmark, 30-day window, one later note"),
        run(con, "landmark k = 3", "less time for a verdict to arrive before classification", k=3),
        run(con, "landmark k = 14", "more time for a verdict to arrive before classification", k=14),
        run(
            con,
            "excluding not-misleading first notes",
            "these notes are structurally barred from Helpful; promoted to a headline "
            "robustness number at Gate 1",
            where="NOT flag_not_misleading",
        ),
        run(
            con,
            "retention = two or more later notes",
            "a stricter definition of still contributing",
            min_notes=2,
        ),
        run(
            con,
            "cohorts with 90+ days observed after the window",
            "drops the most recent cohorts entirely",
            where=obs_90,
        ),
    ]

    TABLES.mkdir(parents=True, exist_ok=True)
    with open(TABLES / "robustness.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(variations[0].keys()))
        w.writeheader()
        w.writerows(variations)

    base = variations[0]["difference_pp"]
    swing = max(abs(v["difference_pp"] - base) for v in variations[1:])
    signs = {v["difference_pp"] < 0 for v in variations}

    L = [
        "# Robustness (M7)",
        "",
        f"The Not Helpful minus NMR difference is negative in every variation, ranging from "
        f"{min(v['difference_pp'] for v in variations):+.1f} to "
        f"{max(v['difference_pp'] for v in variations):+.1f} pp against a baseline of "
        f"{base:+.1f} pp. No sign flip; largest swing {swing:.1f} pp.",
        "",
        "Generated by `src/analysis_robustness.py`. Table in `out/tables/robustness.csv`.",
        "",
        "| variation | n NH | n NMR | NH retention | NMR retention | difference | 95% CI |",
        "| --- | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for v in variations:
        L.append(
            f"| {v['variation']} | {v['n_not_helpful']:,} | {v['n_nmr']:,} | "
            f"{v['retention_not_helpful']:.1%} | {v['retention_nmr']:.1%} | "
            f"{v['difference_pp']:+.1f} pp | {v['ci_low_pp']:+.1f} – {v['ci_high_pp']:+.1f} pp |"
        )

    L += ["", "## Notes on each", ""]
    for v in variations[1:]:
        L.append(f"- **{v['variation']}** — {v['note']}. Moves the difference by "
                 f"{v['difference_pp'] - base:+.1f} pp.")

    L += [
        "",
        "## Reading it",
        "",
        "Nothing here rescues or destroys the headline. "
        + ("Every variation keeps the same sign" if len(signs) == 1 else "One variation flips sign")
        + ", and the spread is small next to the difference between the pooled estimate and the",
        "cohort split in M6c, which is where the real sensitivity lives. The choice that",
        "matters for this project is not the landmark or the window, it is *when* a",
        "contributor joined relative to the 2024-04-02 lockout rule.",
    ]
    (TABLES / "robustness.md").write_text("\n".join(L).rstrip() + "\n")

    print(f"wrote {(TABLES / 'robustness.csv').relative_to(ROOT)}")
    for v in variations:
        print(
            f"  {v['variation']:<46} {v['difference_pp']:+7.2f} pp  "
            f"[{v['ci_low_pp']:+.2f}, {v['ci_high_pp']:+.2f}]  n={v['n_not_helpful']:,}/{v['n_nmr']:,}"
        )


if __name__ == "__main__":
    main()
