"""M6e: logistic regression of 30-day retention on day-7 status, NMR as reference.

Supporting evidence for M6a, not a replacement. If the regression and the raw
proportions disagree, both get reported.

Usage: python src/analysis_logit.py
"""

import csv
from pathlib import Path

import duckdb
import numpy as np
import pandas as pd
import statsmodels.api as sm

import exclusions
import retention

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "out" / "tables"
K = 7
WINDOW = 30

TERMS = {
    "status_Helpful": "Helpful (vs NMR)",
    "status_Not Helpful": "Not Helpful (vs NMR)",
    "not_misleading": "First note says post is not misleading",
    "has_url": "First note contains a URL",
    "note_len_100": "First note length, per 100 characters",
}


def design(con: duckdb.DuckDBPyConnection) -> tuple[pd.DataFrame, pd.Series, list[str]]:
    landmark = retention.landmark_sql(exclusions.analysis_sql(), K)
    tags = [
        r[0]
        for r in con.execute(
            f"SELECT DISTINCT unnest(first_reason_tags) AS t FROM ({landmark}) ORDER BY t"
        ).fetchall()
    ]
    tag_cols = ",\n          ".join(
        f"list_contains(first_reason_tags, '{t}')::INT AS tag_{t}" for t in tags
    )
    df = con.execute(
        f"""
        SELECT retained::INT AS retained, status_k, cohort_month,
          (first_classification = 'NOT_MISLEADING')::INT AS not_misleading,
          first_has_url::INT AS has_url,
          first_note_len / 100.0 AS note_len_100,
          {tag_cols}
        FROM ({retention.retention_sql(landmark, WINDOW)}) WHERE observable
        """
    ).df()

    y = df.pop("retained")
    status = pd.get_dummies(df.pop("status_k"), prefix="status", dtype=float)
    status = status.drop(columns=["status_NMR"])
    cohort = pd.get_dummies(df.pop("cohort_month"), prefix="cohort", drop_first=True, dtype=float)
    X = pd.concat([status, df.astype(float), cohort], axis=1)
    return sm.add_constant(X), y, tags


def main() -> None:
    con = duckdb.connect()
    X, y, tags = design(con)
    print(f"fitting on {len(y):,} authors, {X.shape[1]} parameters")

    res = sm.Logit(y, X).fit(disp=False, maxiter=200)
    ame = res.get_margeff(at="overall", method="dydx")
    ame_by_term = dict(zip(X.columns[1:], zip(ame.margeff, ame.margeff_se)))

    conf = res.conf_int()
    rows = []
    for term in X.columns:
        if term == "const":
            continue
        m, se = ame_by_term[term]
        rows.append(
            {
                "term": term,
                "label": TERMS.get(term, term.replace("tag_", "tag: ")),
                "coef": res.params[term],
                "std_err": res.bse[term],
                "p_value": res.pvalues[term],
                "odds_ratio": np.exp(res.params[term]),
                "or_ci_low": np.exp(conf.loc[term, 0]),
                "or_ci_high": np.exp(conf.loc[term, 1]),
                "marginal_effect_pp": m * 100,
                "ame_ci_low_pp": (m - retention.Z * se) * 100,
                "ame_ci_high_pp": (m + retention.Z * se) * 100,
            }
        )

    TABLES.mkdir(parents=True, exist_ok=True)
    with open(TABLES / "logit.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    key = [r for r in rows if r["term"] in TERMS]
    nh = next(r for r in key if r["term"] == "status_Not Helpful")
    hp = next(r for r in key if r["term"] == "status_Helpful")

    L = [
        "# Logit regression (M6e)",
        "",
        f"Adjusted for cohort month and first-note features, being rated Not Helpful by day "
        f"{K} is associated with a **{nh['marginal_effect_pp']:+.1f} pp** change in the "
        f"probability of writing another note within {WINDOW} days "
        f"(odds ratio {nh['odds_ratio']:.2f}, 95% CI {nh['or_ci_low']:.2f}–{nh['or_ci_high']:.2f}).",
        "",
        "Generated by `src/analysis_logit.py`. Full estimates in `out/tables/logit.csv`.",
        "",
        f"Fitted on {len(y):,} authors with {X.shape[1]} parameters: day-{K} status with NMR as",
        f"the reference, {sum(c.startswith('cohort_') for c in X.columns)} cohort-month fixed",
        f"effects, and first-note controls (classification, whether it cites a URL, length, and",
        f"{len(tags)} reason tags). Marginal effects are averaged over the sample.",
        "",
        "| term | odds ratio | 95% CI | marginal effect | 95% CI |",
        "| --- | ---: | --- | ---: | --- |",
    ]
    for r in key:
        L.append(
            f"| {r['label']} | {r['odds_ratio']:.2f} | {r['or_ci_low']:.2f} – {r['or_ci_high']:.2f} | "
            f"{r['marginal_effect_pp']:+.1f} pp | {r['ame_ci_low_pp']:+.1f} – {r['ame_ci_high_pp']:+.1f} pp |"
        )

    raw = {
        d["comparison"]: d["difference"] * 100
        for d in retention.differences(
            retention.tabulate(con, retention.landmark_sql(exclusions.analysis_sql(), K), windows=[WINDOW])
        )
    }
    raw_nh, raw_hp = raw["Not Helpful - NMR"], raw["Helpful - NMR"]

    L += [
        "",
        "## Against the raw proportions",
        "",
        "| comparison | M6a raw difference | M6e adjusted marginal effect |",
        "| --- | ---: | ---: |",
        f"| Not Helpful − NMR | {raw_nh:+.1f} pp | {nh['marginal_effect_pp']:+.1f} pp |",
        f"| Helpful − NMR | {raw_hp:+.1f} pp | {hp['marginal_effect_pp']:+.1f} pp |",
        "",
        f"Same direction in both cases, but the adjusted Not Helpful estimate is "
        f"{abs(nh['marginal_effect_pp'] - raw_nh):.1f} pp larger than the raw one. That is not a",
        "contradiction, and it is worth saying why rather than picking the more convenient",
        "number. The raw figure pools every cohort together, and M6c shows the gap is small",
        "before 2024-04 and large after. Cohort fixed effects make the comparison within",
        "cohort, which removes the early cohorts' smaller gaps from the average and leaves an",
        "estimate closer to what recent cohorts actually show.",
        "",
        "So the two are consistent, and both understate how much the answer depends on when a",
        "contributor joined. M6c is the table that makes that visible.",
        "",
        "Marginal effects for binary terms are derivatives rather than discrete changes, so",
        "they are close to but not exactly a difference in proportions.",
        "",
        "One control is worth noting on its own. A first note saying the post is **not**",
        f"misleading is associated with {next(r for r in key if r['term'] == 'not_misleading')['marginal_effect_pp']:+.1f} pp retention once status is",
        "held constant, even though such notes are structurally barred from Helpful and reach",
        "Not Helpful far more often. That supports the Gate 1 decision to keep them in the",
        "primary analysis rather than excluding them.",
        "",
        "This is supporting evidence. The headline number is M6a's, because it needs no model.",
    ]
    (TABLES / "logit.md").write_text("\n".join(L).rstrip() + "\n")

    print(f"wrote {(TABLES / 'logit.csv').relative_to(ROOT)} and logit.md")
    for r in key:
        print(
            f"  {r['label']:<42} OR {r['odds_ratio']:>5.2f}  AME {r['marginal_effect_pp']:+6.2f} pp"
        )


if __name__ == "__main__":
    main()
