"""M5: the one place exclusions are applied.

Every downstream analysis gets its sample from `analysis_sample()`. Exclusions are
boolean columns on the frozen contributor table, never deleted rows, so any of them can
be inspected or reversed without rebuilding anything.

Run directly to regenerate docs/exclusions.md.
"""

import json
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[1]
INTERIM = ROOT / "data" / "interim"
TABLE = ROOT / "data" / "processed" / "contributors.parquet"
OUT = ROOT / "docs" / "exclusions.md"

C = f"read_parquet('{TABLE}')"
ENROLL = f"read_parquet('{INTERIM / 'userEnrollment.parquet'}')"

# (column, predicate, why) — decided at HUMAN GATE 1 unless noted.
EXCLUSIONS = [
    (
        "excl_api_author",
        "e.enrollmentState LIKE 'api%'",
        "AI note writers. Matched on the `api` prefix rather than `apiEarnedIn` exactly, "
        "so `apiEarnedOut` and `apiTestUser` are caught if they ever appear. An AI that "
        "stops writing has not given up, which is the thing we are measuring.",
    ),
    (
        "excl_pre_2023_cohort",
        "c.cohort_month < '2023-01'",
        "`firstNonNMRStatus` is empty for every note created before 2022-05 and the rest "
        "of 2022 is contaminated by the 2023-01-20 retro-scoring, so these cohorts cannot "
        "supply a Not Helpful group to compare against.",
    ),
    (
        "excl_first_note_unscored",
        "NOT c.first_note_scored",
        "First note has no `noteStatusHistory` row, so its outcome is unknown rather than "
        "absent. Calling these NMR would inflate the comparison group by an amount that "
        "grows over time and would show up as a fake cohort trend. Decided after Gate 1, "
        "delegated by Kevin; see docs/worklog.md.",
    ),
]

# Not applied. Carried through so M7 and the headline robustness number can use it.
FLAGS = [
    (
        "flag_not_misleading",
        "c.first_classification = 'NOT_MISLEADING'",
        "Notes calling a post not misleading are structurally barred from Helpful: since "
        "2023, 164 reached Helpful against 57,777 Not Helpful. Kept in the primary "
        "analysis at Gate 1, reported separately as robustness.",
    ),
]


def sample_sql() -> str:
    """The frozen table with one boolean column per exclusion and per flag."""
    cols = ",\n      ".join(
        f"({pred}) AS {name}" for name, pred, _ in EXCLUSIONS + FLAGS
    )
    return f"""
    SELECT c.*, e.enrollmentState, e.numberOfTimesEarnedOut,
      e.timestampOfLastStateChange, e.timestampOfLastEarnOut,
      {cols}
    FROM {C} c
    LEFT JOIN {ENROLL} e ON e.participantId = c.author_id
    """


def analysis_sql() -> str:
    """The sample every downstream analysis runs on."""
    keep = " AND ".join(f"NOT {name}" for name, _, _ in EXCLUSIONS)
    return f"SELECT * FROM ({sample_sql()}) WHERE {keep}"


def analysis_sample(con: duckdb.DuckDBPyConnection) -> duckdb.DuckDBPyRelation:
    return con.sql(analysis_sql())


def counts(con: duckdb.DuckDBPyConnection) -> dict:
    names = [n for n, _, _ in EXCLUSIONS]
    total = con.execute(f"SELECT count(*) FROM ({sample_sql()})").fetchone()[0]

    overall = {}
    for name in names:
        alone = con.execute(f"SELECT count(*) FROM ({sample_sql()}) WHERE {name}").fetchone()[0]
        others = " OR ".join(n for n in names if n != name) or "FALSE"
        only = con.execute(
            f"SELECT count(*) FROM ({sample_sql()}) WHERE {name} AND NOT ({others})"
        ).fetchone()[0]
        overall[name] = {"excluded": alone, "excluded_only_by_this": only}

    kept = con.execute(f"SELECT count(*) FROM ({analysis_sql()})").fetchone()[0]
    flagged = {
        name: con.execute(f"SELECT count(*) FROM ({analysis_sql()}) WHERE {name}").fetchone()[0]
        for name, _, _ in FLAGS
    }

    by_cohort = con.execute(
        f"""
        SELECT cohort_month,
               count(*) AS authors,
               {', '.join(f'count(*) FILTER (WHERE {n}) AS {n}' for n in names)},
               count(*) FILTER (WHERE {' AND '.join(f'NOT {n}' for n in names)}) AS kept
        FROM ({sample_sql()})
        WHERE cohort_month >= '2023-01'
        GROUP BY 1 ORDER BY 1
        """
    ).fetchall()

    return {
        "total_authors": total,
        "kept": kept,
        "overall": overall,
        "flagged_in_sample": flagged,
        "by_cohort": by_cohort,
        "cohort_columns": ["cohort_month", "authors"] + names + ["kept"],
    }


def render(snapshot: str, c: dict) -> str:
    L = [
        "# Exclusions (M5)",
        "",
        f"Snapshot **{snapshot}**. Generated by `src/exclusions.py`. Do not hand-edit.",
        "",
        "Exclusions are boolean columns on the frozen contributor table, not deleted rows.",
        "`src/exclusions.py:analysis_sample()` is the only way downstream analyses get a",
        "sample, so nothing can quietly use a different one.",
        "",
        f"**{c['total_authors']:,} authors in the frozen table → {c['kept']:,} in the "
        f"analysis sample** ({c['kept'] / c['total_authors']:.1%}).",
        "",
        "## Applied",
        "",
        "| exclusion | authors removed | removed by this alone |",
        "| --- | ---: | ---: |",
    ]
    for name, _, _ in EXCLUSIONS:
        o = c["overall"][name]
        L.append(f"| `{name}` | {o['excluded']:,} | {o['excluded_only_by_this']:,} |")
    L += [
        "",
        "Exclusions overlap, so the first column does not sum to the total removed. The",
        "second column counts authors this exclusion alone is responsible for.",
        "",
    ]
    for name, _, why in EXCLUSIONS:
        L += [f"**`{name}`** — {why}", ""]

    L += ["## Carried but not applied", ""]
    for name, _, why in FLAGS:
        L += [f"**`{name}`** — {why}", "", f"In the analysis sample: {c['flagged_in_sample'][name]:,} authors.", ""]

    L += [
        "## By cohort month",
        "",
        "| " + " | ".join(c["cohort_columns"]) + " |",
        "| " + " | ".join(["---"] + ["---:"] * (len(c["cohort_columns"]) - 1)) + " |",
    ]
    for row in c["by_cohort"]:
        L.append("| " + " | ".join(str(v) if i == 0 else f"{v:,}" for i, v in enumerate(row)) + " |")
    return "\n".join(L).rstrip() + "\n"


def main() -> None:
    snapshot = json.loads((INTERIM / "row_counts.json").read_text())["snapshot"]
    con = duckdb.connect()
    c = counts(con)
    OUT.write_text(render(snapshot, c))
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {c['total_authors']:,} authors -> {c['kept']:,} in sample")
    for name, _, _ in EXCLUSIONS:
        print(f"  {name}: {c['overall'][name]['excluded']:,} removed")


if __name__ == "__main__":
    main()
